/**
 * Builds the Go engine into a WebAssembly module and embeds it in the bundle.
 *
 *   node scripts/build-wasm.mjs
 *
 * The app is shipped as a single index.html (vite-plugin-singlefile) and is
 * often opened straight from disk, where fetch("engine.wasm") is blocked, so the
 * module has to travel inside the JavaScript. A 5 MB wasm file is unacceptable
 * inlined, so it is gzipped (1.5 MB) and base64 encoded (~2 MB), then expanded in
 * the worker with DecompressionStream.
 */
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import zlib from "node:zlib";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const engineDir = path.join(root, "engine");
const wasmDir = path.join(root, "src", "wasm");
const rawWasm = path.join(wasmDir, "engine.wasm");

function log(msg) {
  console.log("[build:wasm] " + msg);
}

// 1. go vet + unit tests first: a broken engine should never reach the bundle.
log("running go vet");
execFileSync("go", ["vet", "."], { cwd: engineDir, stdio: "inherit" });
log("running go test");
execFileSync("go", ["test", "./..."], { cwd: engineDir, stdio: "inherit" });

// 2. compile for js/wasm
fs.mkdirSync(wasmDir, { recursive: true });
log("compiling GOOS=js GOARCH=wasm");
execFileSync(
  "go",
  ["build", "-trimpath", "-ldflags=-s -w", "-o", rawWasm, "."],
  { cwd: engineDir, stdio: "inherit", env: { ...process.env, GOOS: "js", GOARCH: "wasm" } },
);

// 3. vendor wasm_exec.js next to the payload so the worker can import it
const goroot = execFileSync("go", ["env", "GOROOT"], { encoding: "utf8" }).trim();
const execSrc = path.join(goroot, "lib", "wasm", "wasm_exec.js");
const execDest = path.join(wasmDir, "wasm_exec.js");
if (!fs.existsSync(execSrc)) {
  throw new Error("wasm_exec.js not found at " + execSrc);
}
fs.copyFileSync(execSrc, execDest);
log("vendored wasm_exec.js (Go " + goroot.split("/").pop() + ")");

// 4. gzip + base64 into a TypeScript module
const wasm = fs.readFileSync(rawWasm);
const gz = zlib.gzipSync(wasm, { level: 9 });
const b64 = gz.toString("base64");
const ts = `// Generated by scripts/build-wasm.mjs - do not edit by hand.
// Source: engine/*.go, compiled with GOOS=js GOARCH=wasm.
// ${wasm.length} bytes of wasm, gzipped to ${gz.length} bytes.
export const ENGINE_WASM_GZIP_BASE64 = ${JSON.stringify(b64)};
`;
fs.writeFileSync(path.join(wasmDir, "engineWasm.ts"), ts);
fs.rmSync(rawWasm, { force: true });

log(
  `engine: ${(wasm.length / 1048576).toFixed(2)} MB wasm -> ` +
    `${(gz.length / 1048576).toFixed(2)} MB gzip -> ${(b64.length / 1048576).toFixed(2)} MB base64`,
);
